In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
# sns.set_style("darkgrid")

In [4]:
df=pd.read_csv("../Zomato/zomato_data1/zomato.csv", encoding='ISO-8859-1')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [13]:
df_country = pd.read_excel("../Zomato/zomato_data1/Country-Code.xlsx")
df_country.head()

   Country Code    Country
0             1      India
1            14  Australia
2            30     Brazil
3            37     Canada
4            94  Indonesia

In [14]:
df_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Code  15 non-null     int64
 1   Country       15 non-null     object
dtypes: int64(1), object(1)
memory usage: 368.0+ bytes

In [15]:
merged_df = df.merge(df_country, on="Country Code")
merged_df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

In [19]:
merged_df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'Country'],
      dtype='object')

In [22]:
merged_df = merged_df[['Restaurant ID', 'Restaurant Name','Country', 'Country Code', 'City', 'Address','Average Cost for two', 'Currency','Cuisines','Price range', 'Aggregate rating','Locality', 'Locality Verbose',  'Rating text','Votes','Longitude', 'Latitude', 'Has Table booking','Has Online delivery', 'Is delivering now', 'Switch to order menu','Rating color' ]]
merged_df.head()

,Restaurant ID,Restaurant Name,Country,Country Code,City,Address,Average Cost for two,Currency,Cuisines,Price range,...,Locality Verbose,Rating text,Votes,Longitude,Latitude,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Rating color
0,6317637,Le Petit Souffle,Phillipines,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...",1100,Botswana Pula(P),"French, Japanese, Desserts",3,...,"Century City Mall, Poblacion, Makati City, Mak...",Excellent,314,121.027535,14.565443,Yes,No,No,No,Dark Green
1,6304287,Izakaya Kikufuji,Phillipines,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...",1200,Botswana Pula(P),Japanese,3,...,"Little Tokyo, Legaspi Village, Makati City, Ma...",Excellent,591,121.014101,14.553708,Yes,No,No,No,Dark Green
2,6300002,Heat - Edsa Shangri-La,Phillipines,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...",4000,Botswana Pula(P),"Seafood, Asian, Filipino, Indian",4,...,"Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",Very Good,270,121.056831,14.581404,Yes,No,No,No,Green
3,6318506,Ooma,Phillipines,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...",1500,Botswana Pula(P),"Japanese, Sushi",4,...,"SM Megamall, Ortigas, Mandaluyong City, Mandal...",Excellent,365,121.056475,14.585318,No,No,No,No,Dark Green
4,6314302,Sambo Kojin,Phillipines,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...",1500,Botswana Pula(P),"Japanese, Korean",4,...,"SM Megamall, Ortigas, Mandaluyong City, Mandal...",Excellent,229,121.057508,14.584450,Yes,No,No,No,Dark Green

In [23]:
merged_df['Country'].unique()

array(['Phillipines', 'Brazil', 'United States', 'Australia', 'Canada',
       'Singapore', 'UAE', 'India', 'Indonesia', 'New Zealand',
       'United Kingdom', 'Qatar', 'South Africa', 'Sri Lanka', 'Turkey'],
      dtype=object)

In [24]:
India_merged_df=merged_df[merged_df['Country']=='India']
India_merged_df.head()

,Restaurant ID,Restaurant Name,Country,Country Code,City,Address,Average Cost for two,Currency,Cuisines,Price range,...,Locality Verbose,Rating text,Votes,Longitude,Latitude,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Rating color
624,3400025,Jahanpanah,India,1,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",850,Indian Rupees(Rs.),"North Indian, Mughlai",3,...,"Agra Cantt, Agra",Good,140,78.011544,27.161661,No,No,No,No,Yellow
625,3400341,Rangrezz Restaurant,India,1,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",700,Indian Rupees(Rs.),"North Indian, Mughlai",2,...,"Agra Cantt, Agra",Good,71,0.000000,0.000000,No,No,No,No,Yellow
626,3400005,Time2Eat - Mama Chicken,India,1,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",500,Indian Rupees(Rs.),North Indian,2,...,"Agra Cantt, Agra",Good,94,78.011608,27.160832,No,No,No,No,Yellow
627,3400021,Chokho Jeeman Marwari Jain Bhojanalya,India,1,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",400,Indian Rupees(Rs.),Rajasthani,2,...,"Civil Lines, Agra",Very Good,87,77.998092,27.195928,No,No,No,No,Green
628,3400017,Pinch Of Spice,India,1,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",1000,Indian Rupees(Rs.),"North Indian, Chinese, Mughlai",3,...,"Civil Lines, Agra",Very Good,177,78.007553,27.201725,No,No,No,No,Green

In [26]:
India_merged_df['City'].unique()
India_merged_df[India_merged_df['City']=='Agra']

,Restaurant ID,Restaurant Name,Country,Country Code,City,Address,Average Cost for two,Currency,Cuisines,Price range,...,Locality Verbose,Rating text,Votes,Longitude,Latitude,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Rating color
624,3400025,Jahanpanah,India,1,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",850,Indian Rupees(Rs.),"North Indian, Mughlai",3,...,"Agra Cantt, Agra",Good,140,78.011544,27.161661,No,No,No,No,Yellow
625,3400341,Rangrezz Restaurant,India,1,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",700,Indian Rupees(Rs.),"North Indian, Mughlai",2,...,"Agra Cantt, Agra",Good,71,0.000000,0.000000,No,No,No,No,Yellow
626,3400005,Time2Eat - Mama Chicken,India,1,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",500,Indian Rupees(Rs.),North Indian,2,...,"Agra Cantt, Agra",Good,94,78.011608,27.160832,No,No,No,No,Yellow
627,3400021,Chokho Jeeman Marwari Jain Bhojanalya,India,1,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",400,Indian Rupees(Rs.),Rajasthani,2,...,"Civil Lines, Agra",Very Good,87,77.998092,27.195928,No,No,No,No,Green
628,3400017,Pinch Of Spice,India,1,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",1000,Indian Rupees(Rs.),"North Indian, Chinese, Mughlai",3,...,"Civil Lines, Agra",Very Good,177,78.007553,27.201725,No,No,No,No,Green
629,3400325,MoMo Cafe,India,1,Agra,"Courtyard by Marriott Agra, Phase 2, Fatehabad...",2000,Indian Rupees(Rs.),"North Indian, European",4,...,"Courtyard by Marriott Agra, Tajganj, Agra",Very Good,45,0.000000,0.000000,No,No,No,No,Green
630,3400059,Peshawri - ITC Mughal,India,1,Agra,"ITC Mughal, Fatehabad Road, Tajganj, Agra",2500,Indian Rupees(Rs.),"North Indian, Mughlai",4,...,"ITC Mughal, Tajganj, Agra",Very Good,133,78.044095,27.160934,No,No,No,No,Green
631,3400060,Taj Bano - ITC Mughal,India,1,Agra,"ITC Mughal, Fatehabad Road, Tajganj, Agra",2500,Indian Rupees(Rs.),Mughlai,4,...,"ITC Mughal, Tajganj, Agra",Very Good,41,78.044095,27.160934,No,No,No,No,Green
632,3400348,G Thal,India,1,Agra,"3/20, KPS Tower, Near Tulsi Talkies, Bypass Ro...",800,Indian Rupees(Rs.),"Rajasthani, Gujarati, Mughlai",3,...,"Khandari, Agra",Good,59,0.000000,0.000000,No,No,No,No,Yellow
633,3400072,Dawat-e-Nawab - Radisson Blu,India,1,Agra,"Radisson Blu, Taj East Gate Road, Tajganj, Agra",3600,Indian Rupees(Rs.),"North Indian, Mughlai",4,...,"Radisson Blu, Tajganj, Agra",Good,46,78.057044,27.163303,No,No,No,No,Yellow
634,3400073,The Latitude - Radisson Blu,India,1,Agra,"Radisson Blu, Taj East Gate Road, Tajganj, Agra",0,Indian Rupees(Rs.),"North Indian, Chinese, Continental",1,...,"Radisson Blu, Tajganj, Agra",Good,103,78.057044,27.163303,No,No,No,No,Yellow
635,3400019,Dasaprakash Restaurant,India,1,Agra,"Meher Cinema Complex, Gwalior Road, Rakabganj,...",550,Indian Rupees(Rs.),"South Indian, Desserts",2,...,"Rakabganj, Agra",Very Good,121,78.015053,27.165108,No,No,No,No,Green
636,3400033,The Charcoal Chimney,India,1,Agra,"Hotel Samovar, Fatehabad Road, Tajganj, Agra",1100,Indian Rupees(Rs.),"North Indian, Chinese, Continental, Mughlai",3,...,"Tajganj, Agra",Average,70,78.042990,27.159795,No,No,No,No,Orange
637,3400346,Sheroes Hangout,India,1,Agra,"Opposite The Gateway Hotel, Fatehabad Road, Ta...",0,Indian Rupees(Rs.),"Cafe, North Indian, Chinese",1,...,"Tajganj, Agra",Excellent,77,78.040165,27.161850,No,No,No,No,Dark Green
638,3400350,Bon Barbecue,India,1,Agra,"Parador Hotel, 3A-3B, Phase 1, Fatehabad Road,...",1500,Indian Rupees(Rs.),"North Indian, Chinese, Continental",4,...,"Tajganj, Agra",Good,57,0.000000,0.000000,No,No,No,No,Yellow
639,3400391,Chapter 1 Cafe,India,1,Agra,"1374 K/1375 K, 2nd floor, Dinesh Nagar, Fatehb...",0,Indian Rupees(Rs.),"Cafe, Italian, Mexican, North Indian, Continental",1,...,"Tajganj, Agra",Good,98,0.000000,0.000000,No,No,No,No,Yellow
640,3400016,Pind Balluchi,India,1,Agra,"Opposite Saga Emporium, Fatehabad Road, Tajgan...",900,Indian Rupees(Rs.),"North Indian, Mughlai",3,...,"Tajganj, Agra",Good,175,78.047250,27.157772,No,No,No,No,Yellow
641,3400105,Pizza Hut,India,1,Agra,"8, Handicraft Nagar, Fatehabad Road, Tajganj, ...",700,Indian Rupees(Rs.),"Italian, Pizza",2,...,"Tajganj, Agra",Very Good,134,78.034714,27.161694,No,No,No,No,Green
642,3400326,Tea'se Me - Rooftop Tea Boutique,India,1,Agra,"Near Purani Mandi Crossing,Fatehabad Road, Taj...",1000,Indian Rupees(Rs.),"Chinese, Italian, Continental, North Indian",3,...,"Tajganj, Agra",Very Good,166,0.000000,0.000000,No,No,No,No,Green
643,3400392,Thaaliwala,India,1,Agra,"Next To ITC Mughal Hotel, Fatehabad Road, Tajg...",700,Indian Rupees(Rs.),"North Indian, Fast Food",2,...,"Tajganj, Agra",Very Good,168,78.045359,27.158822,No,No,No,No,Green

In [8]:
df['Cuisines'].iloc[:15]

0             French, Japanese, Desserts
1                               Japanese
2       Seafood, Asian, Filipino, Indian
3                        Japanese, Sushi
4                       Japanese, Korean
5                                Chinese
6                        Asian, European
7     Seafood, Filipino, Asian, European
8                European, Asian, Indian
9                               Filipino
10                     Filipino, Mexican
11         American, Ice Cream, Desserts
12                     Filipino, Mexican
13                              Filipino
14                                Korean
Name: Cuisines, dtype: object

In [11]:
Japanese = df[df["Cuisines"].isin(["Japanese"])]
Japanese

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
27,6600379,Sushi Loko,30,BrasÃ­_lia,"SCS 213, Bloco C, Loja 35, Asa Sul, BrasÃ­_lia",Asa Sul,"Asa Sul, BrasÃ­_lia",-47.915667,-15.831000,Japanese,...,Brazilian Real(R$),No,No,No,No,3,3.1,Orange,Average,10
29,6601218,New Koto,30,BrasÃ­_lia,"SCS 212, Bloco B, Loja 26, Asa Sul, BrasÃ­_lia",Asa Sul,"Asa Sul, BrasÃ­_lia",-47.910167,-15.827333,Japanese,...,Brazilian Real(R$),No,No,No,No,4,3.7,Yellow,Good,5
54,7300004,Sushi Leblon,30,Rio de Janeiro,"Rua Dias Ferreira, 256, Leblon, Rio de Janeiro",Leblon,"Leblon, Rio de Janeiro",-43.227000,-22.984167,Japanese,...,Brazilian Real(R$),No,No,No,No,4,4.6,Dark Green,Excellent,25
222,17334390,Soho Hibachi,216,Dalton,"1014 Battlefield Parkway, Fort Oglethorpe, GA ...",Fort Oglethorpe,"Fort Oglethorpe, Dalton",-85.246237,34.952816,Japanese,...,Dollar($),No,No,No,No,1,4.3,Green,Very Good,116
429,17145495,Marukame Udon,216,Rest of Hawaii,"2310 Kuhio Avenue, Honolulu, HI 96815",Waikiki,"Waikiki, Rest of Hawaii",-157.825979,21.279476,Japanese,...,Dollar($),No,No,No,No,1,4.9,Dark Green,Excellent,602
1188,5904,Club Tokyo - Best Western Skycity Hotel,1,Gurgaon,"Best Western Skycity Hotel, 1 Old Judicial Com...","Best Western Skycity Hotel, Sector 15, Gurgaon","Best Western Skycity Hotel, Sector 15, Gurgaon...",77.034715,28.458088,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,2.8,Orange,Average,13
1466,309125,Kuuraku,1,Gurgaon,"Ground Floor, Global Foyer Mall, Golf Course R...","Global Foyer Mall, Golf Course Road","Global Foyer Mall, Golf Course Road, Gurgaon",77.094699,28.460409,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,3.9,Yellow,Good,106
1517,7472,Daikichi,1,Gurgaon,"UGF-02, JMD Regent Arcade Mall, MG Road, Gurgaon","JMD Regent Arcade Mall, MG Road","JMD Regent Arcade Mall, MG Road, Gurgaon",77.088688,28.479789,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,3.6,Yellow,Good,70
1537,3582,Komachi,1,Gurgaon,"TF 3A/3B/3C, 3rd Floor, MGF Plaza Mall, MG Roa...",MG Road,"MG Road, Gurgaon",77.073107,28.477635,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,3.2,Orange,Average,39
2171,304279,Tokyo,1,Gurgaon,"The Habitare Hotel, 21/1, MG Road, Sector 14, ...","The Habitare Hotel, Sector 14","The Habitare Hotel, Sector 14, Gurgaon",77.040090,28.466142,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,3.0,Orange,Average,10
2181,2710,Konomi - Trident Gurgaon,1,Gurgaon,"Trident, 443, Phase 5, Udyog Vihar, Gurgaon","Trident, Udyog Vihar","Trident, Udyog Vihar, Gurgaon",77.086799,28.502287,Japanese,...,Indian Rupees(Rs.),No,No,No,No,4,3.5,Yellow,Good,27
3102,310123,Fuji Japanese Restaurant,1,New Delhi,"M-41/2, Speedbird House, Middle Circle, Connau...",Connaught Place,"Connaught Place, New Delhi",77.221930,28.632984,Japanese,...,Indian Rupees(Rs.),Yes,Yes,No,No,4,4.0,Green,Very Good,312
3809,2217,Tamura,1,New Delhi,"S-16, Uphar Commercial Complex, Green Park Ext...",Green Park,"Green Park, New Delhi",77.206294,28.558052,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,3.5,Yellow,Good,163
4335,307342,Tamura,1,New Delhi,"TDI Centre, 1st Floor, Jasola, New Delhi",Jasola,"Jasola, New Delhi",77.287463,28.537472,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,3.3,Orange,Average,19
5417,18467388,Manami Japanese Restaurant,1,New Delhi,"Avalon Hotel, Near Sultanpur Metro Station, Su...",MG Road,"MG Road, New Delhi",77.160488,28.496826,Japanese,...,Indian Rupees(Rs.),Yes,No,No,No,3,0.0,White,Not rated,0
9289,7421967,3 Wise Monkeys,94,Jakarta,"Jl. Suryo No. 26, Senopati, Jakarta",Senopati,"Senopati, Jakarta",106.813400,-6.235241,Japanese,...,Indonesian Rupiah(IDR),No,No,No,No,3,4.2,Green,Very Good,395